# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d69e35131c1ffdf8797fb3200db54cc738a8d971973b60f0dfd96617c87c967f9e4f71fd09929aa0afc004f9117e1e406744afc6dc7a995ee78d9b2b0feb2ce4

test:
  secret_key_base: 1036e182d7700e4f9264406286eeb8531b5a8cb0d713c772a15f5dee63e1b77d268e1025ddb783c3947b4ea48cb3abbe64422ec25aff65c31a45ff7765cd05eb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
